plugins: # List of plugins of use on application
    - serverless-offline # Get your serverless configuration and run the server local
    - serverless-plugin-typescript-express

# Project name on the infrastructure created
service: authentication

provider:
  name: aws # Provider name, where the infrastructure has be created
  runtime: nodejs12.x # The node version where the lambda functions going to run
  stage: api # Control the environment of application
  region: us-east-1 # Default region where the lambda functions running

functions: # The array with definitions of lambda functions of the your application 
  # Real Endpoints
  signin:
    handler: src/server.handler
    events:
      - http:
          path: v1/users/signin
          method: post
  signup:
    handler: src/server.handler
    events:
      - http:
          path: v1/users/signup
          method: post
  current-user:
    handler: src/server.handler
    events:
      - http:
          path: v1/users/current-user
          method: get